name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get clean
          sudo apt-get autoclean
          sudo apt-get install -y build-essential make gcc libcunit1 libcunit1-dev bats git

      - name: Build the project
        run: |
          sudo apt-get install -y make
          make -f Makefile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libcunit1 libcunit1-dev bats

      - name: Compile and run tests
        run: |
          gcc ./tests/test_jeu.c ./jeu.c -o jeu_cunits -lcunit
          gcc ./tests/test_statistiques.c ./jeu.c ./statistiques.c -o statistiques_cunits -lcunit
          ./jeu_cunits
          ./statistiques_cunits

      - name: Run BATS tests
        run: bats tests/bataille_navale.bats
